增加一些直播相关功能
MoyuScript/bilibili-api pull request #230
Opened 2021-09-22 06:24 UTC by bakashigure

增加了一些直播相关的功能，包括大航海签到、直播赠送礼物、领取航海日志奖励、获取航海信息、获取自己开通的大航海列表、获取礼物包裹等

以下为`test_live.py`中新增的项目，`send_gift`的参数都需要改一下才能跑
我自己的测试报告: [github action](https://github.com/bakashigure/bilibili-api/actions/runs/1260531844)
```
async def test_p_sign_up_dahanghai():
    return await l.sign_up_dahanghai()

async def test_q_send_gift():
    return await l.send_gift(5702480, 254617846,30725,1)

async def test_r_receive_reward():
    return await l.receive_reward(2)

async def test_s_get_general_info():
    return await l.get_general_info(660303135)

async def test_t_get_self_live_info():
    return await live.get_self_live_info(get_credential())

async def test_u_get_self_guards():
    return await live.get_self_guards(get_credential())

async def test_v_get_self_bag():
    return await live.get_self_bag(get_credential())
```

2021-09-22 12:50 UTC, MoyuScript commented
修了一些格式和代码漏写造成的问题，但是仍然有测试用例未通过，请检查：
```
测试：test_p_sign_up_dahanghai   [FAILED]

Traceback (most recent call last):
  File "D:\Codes\bilibili-api\bilibili_api\utils\network.py", line 115, in request
    resp.raise_for_status()
  File "F:\Python39\lib\site-packages\aiohttp\client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.live.bilibili.com/xlive/activity-interface/v2/userTask/UserTaskSignUp')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Codes\bilibili-api\tests\main.py", line 54, in test
    res = await func()
  File "D:\Codes\bilibili-api\tests\test_live.py", line 66, in test_p_sign_up_dahanghai
    return await l.sign_up_dahanghai()
  File "D:\Codes\bilibili-api\bilibili_api\live.py", line 342, in sign_up_dahanghai
    return await request(api['method'], api["url"], data=data, credential=self.credential)
  File "D:\Codes\bilibili-api\bilibili_api\utils\network.py", line 117, in request
    raise NetworkException(e.status, e.message)
bilibili_api.exceptions.NetworkException.NetworkException: 网络错误，状态码：400 - Bad Request。

测试：test_q_send_gift   [FAILED]

Traceback (most recent call last):
  File "D:\Codes\bilibili-api\tests\main.py", line 54, in test
    res = await func()
  File "D:\Codes\bilibili-api\tests\test_live.py", line 69, in test_q_send_gift
    return await l.send_gift(5702480, 254617846, 30725, 1)
  File "D:\Codes\bilibili-api\bilibili_api\live.py", line 381, in send_gift
    return await request(api['method'], api["url"], data=data, credential=self.credential)
  File "D:\Codes\bilibili-api\bilibili_api\utils\network.py", line 154, in request
    raise ResponseCodeException(code, msg, resp_data)
bilibili_api.exceptions.ResponseCodeException.ResponseCodeException: 接口返回错误代码：-400，信息：Key: 'SendGiftBagReq.Ruid' Error:Field validation for 'Ruid' failed on the 'required' tag。
```

2021-09-22 19:26 UTC, bakashigure commented
重新修改了一下...  似乎是能通过测试了 [test](https://github.com/bakashigure/bilibili-api/actions/runs/1260531844)
好奇怪，之前测试是好好的，可能是某个commit被我误操作给删掉了..

2021-09-23 03:04 UTC, MoyuScript commented
还是失败：

```
测试：test_p_sign_up_dahanghai   [FAILED]

Traceback (most recent call last):
  File "D:\Codes\bilibili-api\bilibili_api\utils\network.py", line 115, in request
    resp.raise_for_status()
  File "F:\Python39\lib\site-packages\aiohttp\client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.live.bilibili.com/xlive/activity-interface/v2/userTask/UserTaskSignUp')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Codes\bilibili-api\tests\main.py", line 54, in test
    res = await func()
  File "D:\Codes\bilibili-api\tests\test_live.py", line 66, in test_p_sign_up_dahanghai
    return await l.sign_up_dahanghai()
  File "D:\Codes\bilibili-api\bilibili_api\live.py", line 342, in sign_up_dahanghai
    return await request(api['method'], api["url"], data=data, credential=self.credential)
  File "D:\Codes\bilibili-api\bilibili_api\utils\network.py", line 117, in request
    raise NetworkException(e.status, e.message)
bilibili_api.exceptions.NetworkException.NetworkException: 网络错误，状态码：400 - Bad Request。

测试：test_q_send_gift   [FAILED]

Traceback (most recent call last):
  File "D:\Codes\bilibili-api\tests\main.py", line 54, in test
    res = await func()
  File "D:\Codes\bilibili-api\tests\test_live.py", line 69, in test_q_send_gift
    return await l.send_gift(5702480, 254617846, 30725, 1)
  File "D:\Codes\bilibili-api\bilibili_api\live.py", line 381, in send_gift
    return await request(api['method'], api["url"], data=data, credential=self.credential)
  File "D:\Codes\bilibili-api\bilibili_api\utils\network.py", line 154, in request
    raise ResponseCodeException(code, msg, resp_data)
bilibili_api.exceptions.ResponseCodeException.ResponseCodeException: 接口返回错误代码：200161，信息：获取包裹数据失败。
```

测试环境：Python 3.9

测试代码：

```bash
@echo off

SET BILI_SESSDATA=[SECRET]
SET BILI_CSRF=[SECRET]
SET BILI_BUVID3=[SECRET]
SET BILI_RATELIMIT=0.1

python -m tests.main -m test_live
``` 

Commit: eccc526d1eb433712466ba9ccb2a7acdce8f3634

2021-09-23 03:27 UTC, bakashigure commented on bilibili_api/data/api/live.json
> +      "method": "POST",
多个一个空格....

2021-09-23 03:33 UTC, bakashigure commented
我....  
`sign_up_dahanghai`的`method`中多了一个空格， 已经删掉了， `send_gift`我测试是没有问题的，换了一个新的包裹测试也可以正常赠送礼物，可能是阿b内部的问题
![image](https://user-images.githubusercontent.com/33803916/134450917-5a7a075c-b97a-46e5-949c-e5acdbe340cf.png)

测试报告
```
(py39_dahanghai) E:\Code\bilibili-api>test.bat
::group::=========== 开始测试 tests.test_live ===========
测试：test_a_get_room_info   [PASSED]
{'room_info': {'uid': 660303135, 'room_id': 22544798, 'short_id': 0, 'title': '地铁：吓死人', 'cover': 'ht
测试：test_b_get_room_play_info   [PASSED]
{'room_id': 22544798, 'short_id': 0, 'uid': 660303135, 'need_p2p': 0, 'is_hidden': False, 'is_locked
测试：test_c_get_room_play_info_v2   [PASSED]
{'room_id': 22544798, 'short_id': 0, 'uid': 660303135, 'is_hidden': False, 'is_locked': False, 'is_p
测试：test_d_get_room_play_url   [PASSED]
{'current_qn': 10000, 'quality_description': [{'qn': 10000, 'desc': '原画'}], 'durl': [{'url': 'https:
测试：test_e_get_user_info_in_room   [PASSED]
{'user_level': {'level': 24, 'next_level': 25, 'color': 5805790, 'level_rank': '>50000'}, 'vip': {'v
测试：test_f_get_dahanghai   [PASSED]
{'info': {'num': 0, 'page': 1, 'now': 1, 'achievement_level': 1}, 'list': [], 'top3': [], 'my_follow
测试：test_g_get_serven_rank   [PASSED]
{'list': [], 'own': {'uid': 5702480, 'uname': '', 'face': '', 'rank': -1, 'score': 0, 'guard_level':
测试：test_h_get_fans_medal_rank   [PASSED]
{'medal': {'status': 0}, 'own': {'uid': 5702480, 'uname': '', 'face': '', 'target_id': 0, 'medal_nam
测试：test_i_get_self_info   [PASSED]
{'uid': 5702480, 'uname': '废紙时雨Official', 'face': 'https://i2.hdslb.com/bfs/face/b6c488ddeeb582534cb
测试：test_j_get_chat_conf   [PASSED]
{'refresh_row_factor': 0.125, 'refresh_rate': 100, 'max_delay': 5000, 'port': 2243, 'host': 'broadca
测试：test_k_ban_user   [FAILED]

Traceback (most recent call last):
  File "E:\Code\bilibili-api\tests\main.py", line 54, in test
    res = await func()
  File "E:\Code\bilibili-api\tests\test_live.py", line 39, in test_k_ban_user
    return await l.ban_user(1)
  File "E:\Code\bilibili-api\bilibili_api\live.py", line 287, in ban_user
    return await request(api['method'], api["url"], data=data, credential=self.credential)
  File "E:\Code\bilibili-api\bilibili_api\utils\network.py", line 154, in request
    raise ResponseCodeException(code, msg, resp_data)
bilibili_api.exceptions.ResponseCodeException.ResponseCodeException: 接口返回错误代码：1200000，信息：你没有权限哦。

测试：test_l_get_black_list   [FAILED]

Traceback (most recent call last):
  File "E:\Code\bilibili-api\tests\main.py", line 54, in test
    res = await func()
  File "E:\Code\bilibili-api\tests\test_live.py", line 45, in test_l_get_black_list
    black_list = await l.get_black_list()
  File "E:\Code\bilibili-api\bilibili_api\live.py", line 226, in get_black_list
    return await request(api['method'], api["url"], params, credential=self.credential)
  File "E:\Code\bilibili-api\bilibili_api\utils\network.py", line 154, in request
    raise ResponseCodeException(code, msg, resp_data)
bilibili_api.exceptions.ResponseCodeException.ResponseCodeException: 接口返回错误代码：1200000，信息：不是管理员。

测试：test_m_unban_user   [FAILED]

Traceback (most recent call last):
  File "E:\Code\bilibili-api\tests\main.py", line 54, in test
    res = await func()
  File "E:\Code\bilibili-api\tests\test_live.py", line 49, in test_m_unban_user
    for item in black_list["data"]:
TypeError: 'NoneType' object is not subscriptable

测试：test_n_send_danmaku   [PASSED]
[]
测试：test_o_LiveDanmaku   [22544798][2021-09-23 11:24:12,926][INFO] 准备连接直播间 22544798
[22544798][2021-09-23 11:24:12,926][DEBUG] 正在获取真实房间号
[22544798][2021-09-23 11:24:12,965][DEBUG] 获取成功，真实房间号：22544798
[22544798][2021-09-23 11:24:12,966][DEBUG] 正在获取聊天服务器配置
[22544798][2021-09-23 11:24:13,002][DEBUG] 聊天服务器配置获取成功
[22544798][2021-09-23 11:24:13,003][DEBUG] 准备连接直播间
[22544798][2021-09-23 11:24:13,003][INFO] 正在尝试连接主机： wss://broadcastlv.chat.bilibili.com:443/sub
[22544798][2021-09-23 11:24:14,839][DEBUG] 连接主机成功, 准备发送认证信息
[22544798][2021-09-23 11:24:14,840][DEBUG] 发送心跳包
[22544798][2021-09-23 11:24:14,848][DEBUG] 收到信息：[{'protocol_version': 1, 'datapack_type': 8, 'data': {'code': 0}}]
[22544798][2021-09-23 11:24:14,849][INFO] 连接服务器并认证成功
[22544798][2021-09-23 11:24:14,849][DEBUG] 收到信息：[{'protocol_version': 1, 'datapack_type': 3, 'data': {'view': 1}}]
[22544798][2021-09-23 11:24:14,849][DEBUG] 收到心跳包反馈
{'room_display_id': 22544798, 'room_real_id': 22544798, 'type': 'VIEW', 'data': 1}
[22544798][2021-09-23 11:24:14,850][INFO] 连接正在关闭
[PASSED]
[22544798][2021-09-23 11:24:14,850][INFO] 连接已关闭
测试：test_p_sign_up_dahanghai   [PASSED]
{'status': 0, 'msg': ''}
测试：test_q_send_gift   [PASSED]
{'uid': 5702480, 'uname': '废紙时雨Official', 'face': 'http://i2.hdslb.com/bfs/face/b6c488ddeeb582534cb7
测试：test_r_receive_reward   [PASSED]
{'status_code': 2, 'status_message': '暂未开启星令', 'awards_list': None}
测试：test_s_get_general_info   [PASSED]
{'subData': {'anchorName': '摸鱼Script', 'countDown': 8, 'openStatus': 0, 'payNum': 0, 'level': 0, 'sc
测试：test_t_get_self_live_info   [PASSED]
{'room_id': 767208, 'main_site_level_rank': 10000, 'master': {'level': 10, 'current': 26882, 'next':
测试：test_u_get_self_guards   [PASSED]
{'list': [{'ruid': 2848871, 'rusername': 'Ripot1an', 'guard_level': 3, 'room_id': 11752002, 'expired
测试：test_v_get_self_bag   [PASSED]
{'list': [{'bag_id': 80075, 'gift_id': 31008, 'gift_name': '你最棒', 'gift_num': 11, 'gift_type': 0, 'e
=========== 结束测试 tests.test_live ===========
::endgroup::
19 passed, 3 failed.
耗时 0:00:06.133783
```

测试环境: Python 3.9.7

2021-09-23 03:36 UTC, MoyuScript commented
你这个礼物是金瓜子还是银瓜子，我这边去送银瓜子的辣条接口不一样：

https://api.live.bilibili.com/xlive/revenue/v1/gift/sendSilver

2021-09-23 03:44 UTC, bakashigure commented
刚刚爬了一下，赠送礼物有三个接口，分别是送银瓜子购买的、送金瓜子购买的、送背包中已有的项目。
```
/xlive/revenue/v1/gift/sendSilver
/xlive/revenue/v1/gift/sendGold
/xlive/revenue/v1/gift/sendBag
```

是我没考虑仔细，我去修改之后再来提pr  打扰了(

2021-09-23 03:45 UTC, MoyuScript commented
就在这个 pr 改就行了

2021-09-23 04:11 UTC, MoyuScript commented
可以写成三个接口：`send_gift_silver` `send_gift_gold` `send_gift_from_bag`

2021-09-25 02:16 UTC, bakashigure commented
把赠送礼物分成三个了：`send_gift_silver` `send_gift_gold` `send_gift_from_bag`， `send_gift_gold`测试成本极高(

新增了获取当前直播间内普通礼物的获取接口`get_gift_common` 如下图黄框内的礼物
![image](https://user-images.githubusercontent.com/33803916/134754325-4a2a5623-a379-494d-a616-f7c4733e1cc2.png)

新增了获取当前直播间内特权/定制礼物的获取接口`get_gift_special` 如下图绿框内的礼物
![image](https://user-images.githubusercontent.com/33803916/134754376-b7f4486a-30f3-4461-b32f-e42983fb0b2d.png)

新增了获取所有直播礼物的接口`get_gift_config` ，这个接口接受三个参数，我这里测试下来似乎只有同时填了三个的时候，返回值才会变化，比如`get_gift_config(245083,443,6)` ,将会得到一个格式化后1.5w行的json, 而任意留空1-3个则会得到一个2.8w行的json。

新增了获取所有分区信息的接口`get_area_info` 就是用来获取`area_parent_id`和`area_id`的。

2021-09-26 04:31 UTC, MoyuScript requested changes
功能是没问题了，但是格式有点问题

2021-09-26 04:31 UTC, MoyuScript commented on bilibili_api/live.py
> +    获取所有礼物的信息，包括礼物 id、名称、价格、等级等。
请说明各参数

2021-09-26 04:31 UTC, MoyuScript commented on bilibili_api/live.py
> +            uid (int)       : 用户 UID
参数注释和实际不匹配，如果是不可修改的参数请直接写死，不要传入

2021-09-26 04:31 UTC, MoyuScript commented on bilibili_api/live.py
> +            uid (int)       : 用户 UID
参数注释和实际不匹配，如果是不可修改的参数请直接写死，不要传入

2021-09-26 04:31 UTC, MoyuScript commented on bilibili_api/live.py
> +            tab_id (int) : 特权礼物:2  , 定制礼物:3
参数注释和实际不匹配，如果是不可修改的参数请直接写死，不要传入

另外，参数类型标为 int，默认值却为 str，如果一定要传入应该设置为 None

2021-09-26 04:31 UTC, MoyuScript commented on bilibili_api/live.py
> +    async def get_gift_common(self, area_id: int = "", area_parent_id: int = ""):
参数类型标为 int，默认值却为 str，如果一定要传入应该设置为 None

2021-09-26 04:31 UTC, MoyuScript commented on bilibili_api/live.py
> +            uid (int)       : 用户 UID
参数注释和实际不匹配，如果是不可修改的参数请直接写死，不要传入

2021-09-27 16:35 UTC, bakashigure commented on bilibili_api/live.py
> +    获取所有礼物的信息，包括礼物 id、名称、价格、等级等。
参数留None会报错、、 不知道该怎么写这个， 先改成str了
```
async def get_gift_config(room_id: int = None,
                          area_id: int = None,
                          area_parent_id: int = None):
    """
    获取所有礼物的信息，包括礼物 id、名称、价格、等级等。
    同时填了 room_id、area_id、area_parent_id，则返回一个较小的 json，只包含该房间、该子区域、父区域的礼物。
    但即使限定了三个条件，仍然会返回约 1.5w 行的 json。不加限定则是 2.8w 行。

    Args:
        room_id (int, optional)         : 房间显示id. Defaults to None.
        area_id (int, optional)         : 子分区id. Defaults to None.
        area_parent_id (int, optional)  : 分区id. Defaults to None.
    """
    api = API["info"]["gift_config"]
    params = {
        "platform": "pc",
        "source": "live",
        "room_id": room_id,
        "area_id": area_id,
        "area_parent_id": area_parent_id,

    }
    return await request(api['method'], api["url"], params=params)
```


```
测试：test_w_get_gift_config   [FAILED]

Traceback (most recent call last):
  File "E:\Code\bilibili-api\tests\main.py", line 54, in test
    res = await func()
  File "E:\Code\bilibili-api\tests\test_live.py", line 111, in test_w_get_gift_config
    return await live.get_gift_config()
  File "E:\Code\bilibili-api\bilibili_api\live.py", line 968, in get_gift_config
    return await request(api['method'], api["url"], params=params)
  File "E:\Code\bilibili-api\bilibili_api\utils\network.py", line 111, in request
    async with session.request(**config) as resp:
  File "D:\Anaconda3_2020_11\envs\py39_dahanghai\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "D:\Anaconda3_2020_11\envs\py39_dahanghai\lib\site-packages\aiohttp\client.py", line 492, in _request
    req = self._request_class(
  File "D:\Anaconda3_2020_11\envs\py39_dahanghai\lib\site-packages\aiohttp\client_reqrep.py", line 283, in __init__
    url2 = url.with_query(params)
  File "D:\Anaconda3_2020_11\envs\py39_dahanghai\lib\site-packages\yarl\_url.py", line 983, in with_query
    new_query = self._get_str_query(*args, **kwargs)
  File "D:\Anaconda3_2020_11\envs\py39_dahanghai\lib\site-packages\yarl\_url.py", line 944, in _get_str_query
    query = "&".join(self._query_seq_pairs(quoter, query.items()))
  File "D:\Anaconda3_2020_11\envs\py39_dahanghai\lib\site-packages\yarl\_url.py", line 907, in _query_seq_pairs
    yield quoter(key) + "=" + quoter(cls._query_var(val))
  File "D:\Anaconda3_2020_11\envs\py39_dahanghai\lib\site-packages\yarl\_url.py", line 922, in _query_var
    raise TypeError(
TypeError: Invalid variable type: value should be str, int or float, got None of type <class 'NoneType'>
```

2021-09-27 16:54 UTC, bakashigure commented on bilibili_api/live.py
> +            uid (int)       : 用户 UID
已修改，我搜索了其他人的开源项目，有人把`storm_beat_id`称为`连击数`，但是经过测试我发现无论是何种礼物，连续发送或多个发送，post请求中的`storm_beat_id`仍然为`0`，所以我觉得应该不是连击数，这个参数具体啥作用还是未知。

2021-09-27 16:56 UTC, bakashigure commented on bilibili_api/live.py
> +            tab_id (int) : 特权礼物:2  , 定制礼物:3
已修改，我写了几行来从直播间信息获取`area_id`和`area_parent_id` ，似乎实现的不太好

2021-09-27 16:56 UTC, bakashigure commented on bilibili_api/live.py
> +            uid (int)       : 用户 UID
已修改注释和实际代码

2021-09-27 16:56 UTC, bakashigure commented on bilibili_api/live.py
> +            uid (int)       : 用户 UID
已修改注释和实际代码

2021-09-27 17:41 UTC, bakashigure commented on bilibili_api/live.py
> +    获取所有礼物的信息，包括礼物 id、名称、价格、等级等。
经过一些测试，

* 房间245083，area_id:443, area_parent_id:6  对应单机游戏-永劫无间，该房间有定制礼物“逗猫棒”
`get_gift_config(room_id=245083,area_id=443,area_parent_id=6)` 可获得房间`245083`的定制礼物`逗猫棒`，14897行
`get_gift_config(room_id=245080,area_id=443,area_parent_id=6)` 无法获得房间`245083`的定制礼物`逗猫棒`，14814行
`get_gift_config(room_id=245083,area_id=114,area_parent_id=514)` 可获得房间`245083`的定制礼物`逗猫棒`，14648行

猜测room_id会实际影响返回值，这三个参数只要有一个空着的或者小于1，就会返回2.7w行
不过即使参数一致，过十几秒钟的返回值和之前的顺序也会发生变化，
我能力有限，无法进一步分析这个api的具体逻辑了...
倒不如不带任何参数，直接拿2.7w行的总表..

2021-09-28 07:42 UTC, merged

2021-09-28 07:42 UTC, MoyuScript commented
辛苦在 https://github.com/MoyuScript/bilibili-api-docs 补充下文档

2021-09-28 11:19 UTC, bakashigure commented
请问文档md是否有排版工具(

2021-09-28 11:20 UTC, MoyuScript commented
> 请问文档md是否有排版工具(

Typora